export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Namma Mart",
  description: "Generated by Namma Mart app",
  icons: {
    icon: "/NM.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head><script src="https://checkout.razorpay.com/v1/checkout.js" async></script></head>

      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <Suspense fallback={<div className="h-20 bg-white" />}>
            <Navbar />
          </Suspense>
          {children}
          <Toaster position="top-center" />
          <Footer />
        </QueryProvider>
      </body>

    </html>
  );
}
